# Generated by Django 3.2.3 on 2021-12-03 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_venda_pessoa'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_venda', models.CharField(max_length=70, verbose_name='Número da venda')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total')),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto')),
                ('impostos', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Impostos')),
                ('nota_fiscal_emitida', models.BooleanField(default=False, verbose_name='Nota fiscal emitida')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.person', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'permissions': [('alterar_nota_fiscal', 'Pode alterar o status de uma nota fiscal')],
            },
        ),
        migrations.AlterField(
            model_name='itemvenda',
            name='venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda', verbose_name='Venda'),
        ),
    ]
