# Generated by Django 3.2.3 on 2021-12-03 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_auto_20211203_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': [('alterar_nota_fiscal', 'Pode alterar o status de uma nota fiscal'), ('visualizar_dashboard', 'Pode visualizar o dashboard')], 'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
    ]
