# Generated by Django 3.2.3 on 2021-06-04 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70, verbose_name='First name')),
                ('last_name', models.CharField(max_length=70, verbose_name='Last name')),
                ('age', models.IntegerField(verbose_name='Age')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Salary')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
    ]
