# Generated by Django 3.2.3 on 2021-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_venda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venda',
            name='desconto',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Desconto'),
        ),
    ]
