# Generated by Django 3.2.3 on 2021-06-14 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='produtos',
            field=models.ManyToManyField(null=True, to='clientes.Produto', verbose_name='Produtos'),
        ),
    ]
