# Generated by Django 3.2.3 on 2021-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_alter_venda_produtos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='valor',
        ),
        migrations.AddField(
            model_name='venda',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Total'),
        ),
    ]
