# Generated by Django 3.2.3 on 2021-11-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20211120_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='nota_fiscal_emitida',
            field=models.BooleanField(default=False, verbose_name='Nota fiscal emitida'),
        ),
    ]
