# Generated by Django 3.2.3 on 2021-11-21 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_venda_nota_fiscal_emitida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='produtos',
        ),
    ]
