# Generated by Django 3.2.3 on 2021-11-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_itemvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemvenda',
            name='desconto',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True, verbose_name='Desconto'),
        ),
    ]
