# Generated by Django 3.2.3 on 2021-11-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_alter_itemvenda_desconto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemVenda',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
