# Generated by Django 3.2.3 on 2021-12-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0016_auto_20211124_1707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
    ]
