# Generated by Django 3.2.3 on 2021-12-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_remove_venda_pessoa'),
        ('vendas', '0002_auto_20211203_1457'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
